export const ActionTypes = {
  // User types
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_REQUEST_ERROR: "USER_LOGIN_REQUEST_ERROR",
  USER_LOGIN_REQUEST_SUCCESS: "USER_LOGIN_REQUEST_SUCCESS",
  USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
  USER_LOGOUT_REQUEST_SUCCESS: "USER_LOGOUT_REQUEST_SUCCESS",
  USER_VERIFY_TOKEN: "USER_VERIFY_TOKEN",
  USER_VERIFY_TOKEN_SUCCESS: "USER_VERIFY_TOKEN_SUCCESS",
};
